osx_image: xcode8.3
language: objective-c
cache:
- bundler
- cocoapods
xcode_workspace: Sabbath Shool.xcworkspace
xcode_scheme: Sabbath School
before_install:
- openssl aes-256-cbc -K $encrypted_142095b63e54_key -iv $encrypted_142095b63e54_iv
  -in ss_certs_travis.enc -out ss_certs_travis -d
- cp ss_certs_travis ~/.ssh/
- chmod 600 ~/.ssh/ss_certs_travis
- cp ss_ssh_config_travis ~/.ssh/config
- bundle install
- bundle exec pod install --repo-update
script:
- bundle exec fastlane beta
