osx_image: xcode11.3
language: objective-c
cache:
- bundler
- cocoapods
xcode_workspace: Sabbath Shool.xcworkspace
xcode_scheme: Sabbath School
before_install:
- openssl aes-256-cbc -K $encrypted_142095b63e54_key -iv $encrypted_142095b63e54_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp ss_certs_travis ~/.ssh/
- chmod 600 ~/.ssh/ss_certs_travis
- cp ss_ssh_config_travis ~/.ssh/config
- bundle install
- bundle exec pod install --repo-update
script:
- bundle exec fastlane travis
env:
  global:
  - secure: lrdpoQMTqljZ0fuz6Pg/PVMfmzhvbTnGKWjYaJaxmtN8l2qMSL6wzZBfm/NYv1XDYEEyMX7LIh6ptnVsKG2zdvX0TLqOmZ5dsh1DodDQIE08yNlYITFJ60lwWPxHvvYCOA78xHSs54wwrFiyxtVxcNiR2HC6fVPSTS0RjFmkEYAAvPCvFOGZGwyImYl923wcyyS2hZrFmgsqsnjfuX5LhmvnR6gtSKyPyNx334XMrAmz+iNNfNp3qyO/qM3V58SWe5YToj6byG+OoJfZnhOeugKjnrH/CvDRc5ty/MPrQ8MGXsIjhdoIknXhx38nQcZla4wtpz9u/anWUFs8zcavPGKvCKP1M208kt/ziBb81DPxBG+REv1OeUhTTeZGpSJKrGzbgkjeWEgLV2B+bJ3jYU6uJMc3RXxPMO1KBmoAs/MijSkqWDCrCrD81H9IkgkGGbXok7kNYQyJX+YkqeYgKPkT8OA5TaDHAMsKGxaBEuaxVv3KNZW1z8q8aauJgmFxwKrrHoco4qarnorgf8nHMGroNqpUShYQ3AP/P25RwKMLqz7Zg/GjvudRHYywk56MJVOeKlmbXS4qNjGb+JS+Ue3h99FB5rwmyo2N4OUn/NFIe7kYDFC+6sclOHqFSmdyPWqYSv9nrI95pqnnSnT1ERGrAGdMdP+52GSUWJ0+8mQ=
  - secure: lIrBYpuRt6b8qiOhhiZJgPZStHYGw36S4yOv7NK+V5ZZwXEyx8X0TP/Wxh79Lyn+Z03RwMWgPU0LwZs9mTVn+eikqK01hFItvAr2TnHYDq90nGdCL3aqwPReYZhPxWsOHAZI7Bn1oisJKmJitozOHXWGNw0Jc6KjgLhQPogVsQd03/h1f3Qbx+XYyhzje6zTCpzxEeioK1IkjwuO0UAtaDkmc+aupdkRF8/NUGpejrf0M1X/wGYUTN3bSANIjJLaKbnup0EdCYiuotvKwd0kToj86i7oot5ItTy5EqnT8LsOhvn45rkWRA4jpPVlloExzqXXyWtZnI89yyF3HrxuxvTyI+O6B2du5hhufqpn2bfpAlgBCn4JTip8SZC/i69QipqGcPpLQtiiYk8GwgAU45oZbsaik23Qz4oxlo5JVpMcdYJjXcnnvXNkzcZnbHas0sREGPUoSsG9TXpebnnNIkBKRwIE6HjzAltGULHiIcAvUlwx9MD90wEBSY9ahZkeJOcecyJZAov2L5FiKhMc58X5pPdhoUMNgY1likZg/HZNFiGnjhPctYj6HLJLAPHLb3uu/2rMcVnw8a/JeDF1jHwmfQ8wb5pK/nhdFbcGs0VeHcNlmVBpjWPtaXS5gCfPxkjZv9JszYvrzAncZBHgwotgZkx0EHdBiMATzVujbl8=
  - secure: OGjbbN/ZXU7lUEX28JdWGflOU+Q36oyP+Na5yeS4mod8PGL36/27nKgEBv+6XEOfxSw/52uTrNxkfzrlO/qbGn3kXAwa7lInxXH3RWA8syd9kC3tLxVcLdmBVKcHx67lL648jwJAZviltEbwSCq6onzgRR8U4WaO0iFIIiBqBuuyR+pMOa3vgnUQCjQZNzEeCHw5K/uW1a9TJPBf4fX1HW9uIiEPF2RDURWfRy1GbYSoWxNyD5embKZ9GW4yuZIZlh9BxNfE+p5jB51g+t2/OuKFMFtjgEd4Os0hYn9zKybNV33jh5ux6Ak3RNPvH1N8ba0qdx7YE18J4DjEBNQ3RwEIBDcUQ60mP7cLj9jp/KSBR2S9879FO0ZQaGVb131/+k/0/aBmuKwlfcAaCUpnBAZUCQ34VsLPZGGsKGARFOy8ZhHePGlPJqR2VuAdjMDXUlVcEtnY0Rq4HfgN1HvTomSRtHwzxcZxzordq8GF5t7L4Bjm9yBdZjnLUdVdRmitwujy6IyoMLlL2Y0fBan1+8d/sZg5v6/Zey10ZbpQgn7jay/9ObdXfpbt3wywhMF4/QMugtOaS3mLLfM31G7q2jKL8e+/Cctf/Hs37FArby9JfOx21HgONaOY1wJV4qMyux4rTUb++35KlESCqCyaVGvnFPi7+b9KnYz5ZzGvj2g=
