# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "7dd5e07e-9fdb-4a2c-8176-894d433097a4"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :travis do
  create_keychain(
    name: ENV["MATCH_KEYCHAIN_NAME"],
    password: ENV["MATCH_PASSWORD"],
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true,
    verbose: true
  )

  match(
    type: "adhoc",
    git_url: "git@bitbucket.org:v1talik/sabbath-school-certificates.git",
    force_for_new_devices: true,
    keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
    keychain_password: ENV["MATCH_PASSWORD"],
    readonly: false
  )

  beta
end

desc "Configure local environment certificates"
  lane :match_config do
  match_sync(type: "development")
  match_sync(type: "adhoc")
end

lane :beta do
  match(
    type: "adhoc",
    git_url: "git@bitbucket.org:v1talik/sabbath-school-certificates.git",
    force_for_new_devices: true,
    readonly: false
  )
  increment_build
  sync_code_signing(type: "appstore")
  build

  crashlytics(
    api_token: File.open("../Fabric.apiKey", "rb").read,
    build_secret: File.open("../Fabric.buildSecret", "rb").read,
    groups: "ios-beta-testers",
    notes: changelog_from_git_commits
  )
end

lane :release do
  match_sync(type: "appstore")
  increment_build
  build(submit: true)
  deliverApp
end

lane :deliverApp do |options|
  submit_for_review = options[:submit]
  deliver(
    submit_for_review: submit_for_review,
    force: true,
    automatic_release: false
  )
end

lane :build do
  gym(
    workspace: "./Sabbath School.xcworkspace",
    scheme: "Sabbath School",
    clean: true,
    include_bitcode: true,
    configuration: "Release",
    output_directory: "./Fastlane/build"
  )
end

desc "Generate screenshots and upload to the App Store"
lane :screenshots do
  sh "export LC_ALL=en_US.UTF-8"
  sh "export LANG=en_US.UTF-8"
  # sh "xcrun simctl list devices | grep -v '^[-=]' | cut -d \"(\" -f2 | cut -d \")\" -f1 | xargs -I {} xcrun simctl erase \"{}\""
  snapshot
  frameit(white: true)
end

desc "Download dSYM files from iTC, upload them to Crashlytics and delete the local dSYM files"
lane :refresh_dsyms do
  download_dsyms
  upload_symbols_to_crashlytics(api_token: File.open("../Fabric.apiKey", "rb").read)
  clean_build_artifacts
end

lane :increment_build do
  date_number = Time.new.strftime("%Y.%m")
  build_number = "#{date_number}.#{number_of_commits}"
  increment_build_number(build_number: build_number)
end

desc "Sync your certificates and profiles across your team using git"
private_lane :match_sync do |options|
  type = options[:type]
  match(
    git_url: "git@bitbucket.org:v1talik/sabbath-school-certificates.git",
    app_identifier: ["com.cryart.SabbathSchool"],
    type: type,
    force_for_new_devices: true
  )
end