# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
# fastlane_version "1.109.0"

default_platform :ios

lane :beta do
  setup_ci(provider: "travis")
  match_sync(type: "appstore")
  increment_build_number
  build
  pilot(api_key_path: "Fastlane/appstore_api_key.json")
end

lane :release do
  match_sync(type: "appstore")
  increment_build_number
  build(submit: true)
  deliverApp
end

lane :deliverApp do |options|
  submit_for_review = options[:submit]
  deliver(
    submit_for_review: submit_for_review,
    force: true,
    automatic_release: false,
    skip_screenshots: true
  )
end

lane :metadata do
  deliver(
    submit_for_review: false,
    force: true,
    automatic_release: false,
    skip_metadata: false,
    skip_screenshots: true,
    skip_binary_upload: true
  )
end

lane :build do
  gym(
    workspace: "./Sabbath School.xcworkspace",
    scheme: "Sabbath School",
    clean: true,
    include_bitcode: true,
    configuration: "Release",
    output_directory: "./Fastlane/build"
  )
end

desc "Generate screenshots and upload to the App Store"
lane :screenshots do
  sh "export LC_ALL=en_US.UTF-8"
  sh "export LANG=en_US.UTF-8"
  # sh "xcrun simctl list devices | grep -v '^[-=]' | cut -d \"(\" -f2 | cut -d \")\" -f1 | xargs -I {} xcrun simctl erase \"{}\""
  snapshot
  frameit(white: true)
end

# lane :increment_build do
#   date_number = Time.new.strftime("%Y.%m")
#   build_number = "#{date_number}.#{number_of_commits}"
#   increment_build_number(build_number: build_number)
# end

desc "Configure local environment certificates"
lane :match_config do
  match_sync(type: "development")
end

# git_url: "https://github.com/Adventech/sabbath-school-certificates.git",
# api_key_path: "Fastlane/appstore_api_key.json"

desc "Sync your certificates and profiles across your team using git"
lane :match_sync do |options|
  type = options[:type]
  match(
    git_url: "git@github.com:Adventech/sabbath-school-certificates.git",
    app_identifier: ["com.cryart.SabbathSchool", "com.cryart.SabbathSchool.Widget"],
    type: type,
    username: "lim.vitaliy@gmail.com"
  )
end