devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPad Pro (12.9-inch)",
  "iPad Pro (9.7-inch)"
])

languages([
  "da", # Danish
  "de-DE", # German
  "en-US", # English
  "es-ES", # Spanish
  "fr-FR", # French
  "ja-JP", # Japanese
  "id", # Indonesian
  "no", # Norwegian
  "pt-BR", # Portuguese
  "ru-RU", # Russian
  "tr-TR", # Turkish
  "zh-Hans" # Chinese
])

scheme "SnapshotUITests"
output_directory "./Fastlane/screenshots"
clear_previous_screenshots false