devices([
  "iPhone 6",
  # "iPhone 6 Plus",
  # "iPhone 5",
  # "iPad Pro (12.9-inch)",
  # "iPad Pro (9.7-inch)"
])

languages([
  "de-DE", # German
  "en-US", # English
  "es-ES", # Spanish
  "fr-CA", # French
  "ja-JP", # Japanese
  ["pt", "pt_BR"], # Portuguese with Brazilian locale
  "ru-RU", # Russian
  "tr-TR", # Turkish
  "uk-UA" # Ukranian
])

scheme "SnapshotUITests"
output_directory "./fastlane/screenshots"
# clear_previous_screenshots true